---
- name: Install Ruby and Bundler
  hosts: all
  become: true
  tasks:

  - name: Install git and ruby
    package:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - git
      - ruby-full
      - ruby-bundler
      - build-essential
